[package]
name = "ferrosa-memory-sync"
version.workspace = true
edition.workspace = true

[dependencies]
ferrosa-memory-core = { path = "../ferrosa-memory-core" }
scylla = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
clap = { version = "4", features = ["derive"] }
