//! Negation must be *additive*: a rule set that uses no negated literal has to
//! evaluate exactly as it did before negation existed.
//!
//! `positive_only_evaluation_matches_the_pre_negation_baseline` is the
//! load-bearing test. Its expected output lives in
//! `tests/fixtures/datalog_pre_negation_digest.txt`, which was generated by
//! running this same fixture against the commit *before* negation was added.
//! The file is therefore a recording of the old engine's behaviour, not a
//! restatement of the new one — any drift in the positive path breaks it.
//!
//! To regenerate after an intentional positive-path change, run with
//! `UPDATE_DATALOG_BASELINE=1`.

use ferrosa_memory_core::datalog::{builtin_rules, evaluate, parse_rule};
use ferrosa_memory_core::types::{DerivedFact, FactSet, Term};
use uuid::Uuid;

fn id(n: u128) -> Term {
    Term::Const(Uuid::from_u128(n))
}

fn s(v: &str) -> Term {
    Term::ConstStr(v.to_string())
}

/// A fixed fact set reaching a broad slice of the builtin rule set:
/// co-occurrence, edges, subclass/instance taxonomy, part-of, activity
/// states, confidence thresholds, tags and dependencies.
fn fixture_facts() -> FactSet {
    let mut f = FactSet::new();
    for (a, b) in [(1u128, 2u128), (2, 3), (3, 4), (4, 1)] {
        f.insert("co_occurs", vec![id(a), id(b)]);
    }
    for (a, b) in [(1u128, 2u128), (2, 3), (3, 5)] {
        f.insert("edge", vec![id(a), s("REL"), id(b)]);
    }
    f.insert("subclass_of", vec![s("dog"), s("mammal")]);
    f.insert("subclass_of", vec![s("mammal"), s("animal")]);
    f.insert("instance_of", vec![id(10), s("dog")]);
    f.insert("part_of", vec![id(20), id(21)]);
    f.insert("part_of", vec![id(21), id(22)]);
    f.insert("active", vec![id(30)]);
    f.insert("dormant", vec![id(31)]);
    f.insert("silent", vec![id(32)]);
    f.insert("unavailable", vec![id(33)]);
    f.insert("confidence", vec![id(40), Term::ConstFloat(0.95.into())]);
    f.insert("confidence", vec![id(41), Term::ConstFloat(0.10.into())]);
    f.insert("tag", vec![id(42), s("curated")]);
    f.insert("tag", vec![id(43), s("skill")]);
    f.insert("depends_on", vec![id(50), id(51)]);
    f
}

/// Canonical, order-independent rendering of an evaluation result.
///
/// Covers every field a caller can observe on a derived fact, so a change to
/// confidence weighting, support counting, rule ids or provenance surfaces
/// here rather than passing silently.
fn digest(facts: &FactSet, derived: &[DerivedFact]) -> String {
    let mut lines: Vec<String> = Vec::new();

    for pred in facts.predicates() {
        if let Some(rows) = facts.get(pred) {
            for args in rows {
                let rendered: Vec<String> = args.iter().map(|t| format!("{t:?}")).collect();
                lines.push(format!("FACT {pred}({})", rendered.join(",")));
            }
        }
    }

    for d in derived {
        let mut prov: Vec<String> = d
            .provenance
            .iter()
            .map(|p| {
                format!(
                    "{}/{}/{}/{}",
                    p.parent_kind, p.parent_pred, p.parent_src, p.parent_dst
                )
            })
            .collect();
        prov.sort();
        lines.push(format!(
            "DERIVED {} {} -> {} conf={:.6} support={} rule={} prov=[{}]",
            d.pred,
            d.src_id,
            d.dst_id,
            d.confidence,
            d.support_count,
            d.rule_id,
            prov.join("|")
        ));
    }

    lines.sort();
    lines.dedup();
    lines.join("\n")
}

fn baseline_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/datalog_pre_negation_digest.txt")
}

#[test]
fn positive_only_evaluation_matches_the_pre_negation_baseline() {
    let rules = builtin_rules();
    let facts = fixture_facts();
    let (all, derived) = evaluate(&rules, &facts, 100, 100_000);
    let actual = digest(&all, &derived);

    let path = baseline_path();
    if std::env::var("UPDATE_DATALOG_BASELINE").is_ok() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &actual).unwrap();
        eprintln!("wrote baseline to {}", path.display());
        return;
    }

    let expected = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "missing pre-negation baseline at {}: {e}. \
             Regenerate on the pre-negation commit with UPDATE_DATALOG_BASELINE=1.",
            path.display()
        )
    });

    assert_eq!(
        actual, expected,
        "the positive evaluation path drifted from its pre-negation behaviour"
    );
}

#[test]
fn a_rule_with_no_negated_literal_keeps_its_pre_negation_rule_id_and_confidence() {
    // The two positive-path formulas negation touched: `format_rule_id`
    // appends nothing when the negated set is empty, and the absence discount
    // in `compute_confidence` is 1.0 when no provenance step is an absence.
    let rules = vec![parse_rule("q(X, Y) :- p(X, Y), r(Y, X).").unwrap()];
    let mut f = FactSet::new();
    f.insert("p", vec![id(1), id(2)]);
    f.insert("r", vec![id(2), id(1)]);

    let (_, derived) = evaluate(&rules, &f, 100, 1000);
    let d = derived.iter().find(|d| d.pred == "q").expect("derived q");

    assert_eq!(d.rule_id, "q:-p,r", "rule id gains no negation segment");
    assert!(!d.rule_id.contains("not "));
    assert_eq!(d.confidence, 0.9, "undiscounted positive confidence");
    assert_eq!(d.support_count, 2);
    assert!(d.provenance.iter().all(|s| s.parent_kind == "base"));
    assert!(d.is_cacheable());
}
