[package]
name = "ferrosa-memory-batch"
version.workspace = true
edition.workspace = true

[dependencies]
ferrosa-memory-core = { path = "../ferrosa-memory-core" }
cdrs-tokio = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
